---

- name: OS dependend variables are loaded
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
    - "default.yml"

- include: prepare.yml
- include: install.yml
- include: configure.yml
